<a href="https://colab.research.google.com/github/boandri/Python_UI_Smart_Devices/blob/main/Activity1_module5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity 1


In [1]:
import tensorflow as tf


In [3]:
x=tf.constant([[5,2],[1,3]])

In [4]:
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 2],
       [1, 3]], dtype=int32)>

In [5]:
print(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


In [6]:
x.numpy()

array([[5, 2],
       [1, 3]], dtype=int32)

In [7]:
x.dtype

tf.int32

In [11]:
x.shape

TensorShape([2, 2])

In [12]:
x.backing_device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [13]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [14]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [15]:
tf.random.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.51981026,  0.47062817,  0.41882718],
       [-1.3320663 , -0.42266133, -0.817917  ]], dtype=float32)>

In [16]:
tf.random.normal(shape=(2,3),mean =5 , stddev=3)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.5728528 ,  6.972598  , -0.41160393],
       [ 5.045861  ,  0.84401417,  7.885689  ]], dtype=float32)>

# Activity2

In [17]:
xvar=tf.random.normal(shape=(3,3))


In [18]:
xvar

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.5586998 ,  0.24332196,  0.07634963],
       [ 0.8809669 , -0.979838  ,  1.824829  ],
       [-0.46442357, -0.5664128 ,  0.5496006 ]], dtype=float32)>

In [19]:
a=tf.Variable(xvar)

In [20]:
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.5586998 ,  0.24332196,  0.07634963],
       [ 0.8809669 , -0.979838  ,  1.824829  ],
       [-0.46442357, -0.5664128 ,  0.5496006 ]], dtype=float32)>

In [22]:
a.assign(tf.random.normal(shape=(3,3)))

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[-0.32870126,  1.2534577 ,  0.42719978],
       [ 2.5303347 , -0.47893125,  2.1879268 ],
       [-1.5075923 , -0.595948  , -1.3945541 ]], dtype=float32)>

In [23]:
xvar_t_add=tf.random.normal(shape=(3,3))

In [24]:
xvar_t_add

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.6097242 ,  0.03999173,  0.28121305],
       [ 0.9766412 ,  1.4913728 ,  0.35746947],
       [-0.7204199 ,  0.4756074 , -1.6424268 ]], dtype=float32)>

In [25]:
a.assign_add(xvar_t_add)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[ 0.28102297,  1.2934494 ,  0.7084128 ],
       [ 3.506976  ,  1.0124416 ,  2.5453963 ],
       [-2.228012  , -0.12034059, -3.036981  ]], dtype=float32)>

In [26]:
a.assign_sub(xvar_t_add)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[-0.32870126,  1.2534577 ,  0.42719978],
       [ 2.5303347 , -0.4789312 ,  2.1879268 ],
       [-1.5075922 , -0.595948  , -1.3945543 ]], dtype=float32)>

In [27]:
new_value=tf.random.normal(shape=(3,3))

In [28]:
new_value

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.9103477 ,  1.5959003 ,  0.7158882 ],
       [-0.17347375, -0.36201698, -1.508201  ],
       [-1.0694511 , -1.6874553 , -0.89345044]], dtype=float32)>

In [29]:
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.32870126,  1.2534577 ,  0.42719978],
       [ 2.5303347 , -0.4789312 ,  2.1879268 ],
       [-1.5075922 , -0.595948  , -1.3945543 ]], dtype=float32)>

In [30]:
a.assign_add(new_value)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[ 1.5816464 ,  2.849358  ,  1.143088  ],
       [ 2.3568609 , -0.84094816,  0.67972577],
       [-2.5770433 , -2.2834034 , -2.2880046 ]], dtype=float32)>

In [31]:
b=tf.random.normal(shape=(3,3))

In [32]:
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3927267 ,  0.5279766 ,  0.2573678 ],
       [ 0.8863101 ,  0.96958077, -0.5625133 ],
       [ 0.34989846, -1.8499855 ,  0.2194147 ]], dtype=float32)>

In [33]:
print(b)

tf.Tensor(
[[ 1.3927267   0.5279766   0.2573678 ]
 [ 0.8863101   0.96958077 -0.5625133 ]
 [ 0.34989846 -1.8499855   0.2194147 ]], shape=(3, 3), dtype=float32)


In [34]:
c = a + b

In [35]:
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.974373  ,  3.3773346 ,  1.4004557 ],
       [ 3.243171  ,  0.1286326 ,  0.11721247],
       [-2.2271447 , -4.133389  , -2.06859   ]], dtype=float32)>

In [36]:
d=tf.square(c)

In [37]:
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[8.8468952e+00, 1.1406389e+01, 1.9612762e+00],
       [1.0518158e+01, 1.6546346e-02, 1.3738764e-02],
       [4.9601736e+00, 1.7084904e+01, 4.2790642e+00]], dtype=float32)>

In [38]:
e=tf.exp(c)

In [40]:
print(e)

tf.Tensor(
[[1.9577347e+01 2.9292589e+01 4.0570483e+00]
 [2.5614817e+01 1.1372721e+00 1.1243584e+00]
 [1.0783590e-01 1.6028466e-02 1.2636384e-01]], shape=(3, 3), dtype=float32)


In [41]:
with tf.GradientTape() as tape:
    tape.watch(a)
    f=tf.sqrt(tf.square(a)+tf.square(b))
    df_da=tape.gradient(f,a)
    print(df_da)

tf.Tensor(
[[ 0.750507   0.9832624  0.9755781]
 [ 0.936004  -0.6552174  0.7704046]
 [-0.990908  -0.7769925 -0.9954333]], shape=(3, 3), dtype=float32)


# Activity3(Example)

In [42]:
import tensorflow as tf

In [43]:
mnist = tf.keras.datasets.mnist

In [44]:
(x_train, y_train),(x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [45]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [46]:
model = tf.keras.models.Sequential([
tf.keras.layers.Flatten(input_shape=(28, 28)),
tf.keras.layers.Dense(128, activation='relu'),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10, activation='softmax')
])

In [47]:
model.compile(optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [48]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2952 - accuracy: 0.9140
Epoch 2/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.1436 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1075 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0871 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0757 - accuracy: 0.9760


In [49]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 2s 5ms/step - loss: 0.0775 - accuracy: 0.9765


[0.07745105028152466, 0.9764999747276306]

## Activity4(Keras Example)

In [50]:
import numpy as np

In [51]:
import tensorflow as tf

In [52]:
from tensorflow import keras

In [53]:
from tensorflow.keras import layers


In [54]:
inputs = keras.Input(shape=(784,)) #2^3*7^2

In [55]:
dense = layers.Dense(64, activation="relu")

In [56]:
x = dense(inputs)

In [57]:
y = layers.Dense(64, activation="relu")(x)

In [58]:
outputs = layers.Dense(10)(y)

In [59]:
model = keras.Model(inputs=inputs, outputs=outputs, name="mnist_model")
#keras.utils.plot_model(model, r"d:\my_first_model.png")
#keras.utils.plot_model(model, r"d:\my_first_model_with_shape_info.png", show_shapes=True)

In [60]:
#Ref: https://keras.io/api/optimizers/
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [61]:
x_train = x_train.reshape(60000, 784).astype("float32") / 255

In [62]:
x_test = x_test.reshape(10000, 784).astype("float32") / 255

In [63]:
model.compile(
loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
optimizer=keras.optimizers.RMSprop(),
metrics=["accuracy"],
)

In [64]:
history = model.fit(x_train, y_train, batch_size=64, epochs=2, validation_split=0.2)

Epoch 1/2
750/750 [==============================] - 8s 8ms/step - loss: 0.3551 - accuracy: 0.8972 - val_loss: 0.1832 - val_accuracy: 0.9477
Epoch 2/2
750/750 [==============================] - 5s 6ms/step - loss: 0.1663 - accuracy: 0.9500 - val_loss: 0.1389 - val_accuracy: 0.9594


In [65]:
test_scores = model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.1382 - accuracy: 0.9598 - 554ms/epoch - 2ms/step


In [66]:
print("Test loss:", test_scores[0])

Test loss: 0.13818281888961792


In [67]:
print("Test accuracy:", test_scores[1])

Test accuracy: 0.9598000049591064
